blog/urls.py
from django.urls import path
from . import views
from django_registration.signals import user_registered

user_registered.connect(views.add_user_to_group_users)

urlpatterns = [

    path('', views.index, name='index'),

    path('blog/all', views.BlogListView.as_view(), name='blog-list'),
    path('blogger/all', views.BloggerListView.as_view(), name='blogger-list'),

    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('blogger/<int:pk>', views.BloggerDetailView.as_view(), name='blogger-detail'),

    path('blog/create', views.BlogCreate.as_view(), name='blog-create'),
    path('blogger/create', views.BloggerCreate.as_view(), name='blogger-create'),

    path('comment/create/<int:pk>', views.CommentCreate.as_view(), name='comment-create'),
]

webdiary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    path('', RedirectView.as_view(url='/blog/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/login/complete/', TemplateView.as_view(template_name='registration/login_complete.html'),
         name='login-complete'),
    path('accounts/logout/complete/', TemplateView.as_view(template_name='registration/logout_complete.html'),
         name='logout-complete'),
    path('blog/', include('blog.urls')),
    ]

blog/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Blogger(models.Model):
    nik_name = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(default=' ', max_length=100)
    last_name = models.CharField(default=' ', max_length=100)
    date_of_birth = models.DateField(blank=True, null=True)
    bio = models.TextField(max_length=1000, help_text='Enter a description')

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def get_absolute_url(self):
        return reverse('blogger-detail', args=[str(self.id)])


class Blog(models.Model):
    blogger = models.ForeignKey(Blogger, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, help_text='Enter a title')
    text = models.TextField(default=' ', max_length=1000, help_text='Enter a content')
    date_of_public = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.id)])


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    text = models.TextField(default=' ', max_length=1000, help_text='Enter a comment')
    date_of_public = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.blog.pk)])

blog/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView

# Create your views here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import Group
from .models import Blogger, Blog, Comment


def index(request):
    num_blogs = Blog.objects.all().count()
    num_bloggers = Blogger.objects.all().count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {

        'num_blogs': num_blogs,
        'num_bloggers': num_bloggers,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context)


class BlogListView(ListView):
    model = Blog
    context_object_name = 'blog_list'
    queryset = Blog.objects.all()
    template_name = 'blog_list.html'


class BlogDetailView(DetailView):
    model = Blog
    context_object_name = 'blog'
    template_name = 'blog_detail.html'

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['comment_list'] = Comment.objects.filter(blog_id=self.kwargs['pk']).order_by('date_of_public')[::-1]
        return context


class BlogCreate(CreateView):
    model = Blog
    fields = ['title', 'text']
    success_url = '/blog/blog/all'
    template_name = 'blog_form.html'

    def form_valid(self, form):
        form.instance.blogger = Blogger.objects.get(nik_name_id=self.request.user.id)
        return super(BlogCreate, self).form_valid(form)


class BloggerListView(ListView):
    model = Blogger
    context_object_name = 'blogger_list'
    queryset = Blogger.objects.all()
    template_name = 'blogger_list.html'


class BloggerDetailView(DetailView):
    model = Blogger
    context_object_name = 'blogger'
    template_name = 'blogger_detail.html'

    def get_context_data(self, **kwargs):
        context = super(BloggerDetailView, self).get_context_data(**kwargs)
        context['blog_list'] = Blog.objects.filter(blogger_id=self.kwargs['pk']).order_by('date_of_public')[::-1]
        return context


class BloggerCreate(LoginRequiredMixin, CreateView):
    model = Blogger
    fields = ['first_name', 'last_name', 'date_of_birth', 'bio']
    success_url = '/blog/blogger/all'
    template_name = 'blogger_form.html'

    def form_valid(self, form):
        form.instance.nik_name = self.request.user
        return super(BloggerCreate, self).form_valid(form)


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['text']
    template_name = 'comment_form.html'

    def form_valid(self, form):
        form.instance.blog = Blog.objects.get(id=self.kwargs['pk'])
        return super(CommentCreate, self).form_valid(form)

    def get_success_url(self):
        return self.object.get_absolute_url()


def add_user_to_group_users(sender, user, **kwargs):
    group = Group.objects.get(name='users')
    group.user_set.add(user)


@receiver(post_save, sender=Blogger)
def add_blogger_to_group_bloggers(sender, instance, **kwargs):
    group = Group.objects.get(name='bloggers')
    group.user_set.add(instance.nik_name)

blog/templates/base.html
<html lang='ru'>
<head>
	<meta charset='utf-8'>
	{% block title %}<title>Платформа для блоггеров</title>{% endblock %}


  	{% load staticfiles %}
	<link rel='stylesheet' type='text/css' href={% static 'css/style.css' %}>
</head>
<body>
	<div class='container'>

			<div class='sidebar'>
				{% block sidebar %}
					<ul class='sidebar-nav'>
						<li><a href='{% url 'index' %}'>Начальная страница</a></li>
						<p></p>
  						<li><a href='{% url 'blog-list' %}'>Все блоги</a></li>
						<p></p>
 						<li><a href='{% url 'blogger-list' %}'>Все блоггеры</a></li>
						<p></p>
                        {% if user.is_authenticated %}
                            <b>Пользователь: {{ user.first_name }} ({{ user.get_username }})</b>

                            {% if perms.blog.add_blog %}
                                    <hr>
                                    <b><a href='{% url 'blog-create' %}'>Создать блог</a></b><br>
                            {% elif perms.blog.add_comment %}
                                    <hr>
                                    <b><a href='{% url 'blogger-create' %}'>Стать блоггером</a></b><br>
                            {% endif %}

							<b><a href='{% url 'logout' %}?next=/accounts/logout/complete/'>Выход</a></b>
						{% else %}
							<p><a href='{% url 'login' %}?next=/accounts/login/complete/'>Вход или регистрация</a></p>
						{% endif %}
					</ul>
				{% endblock %}
			</div>
			<div class='content-nav'>

                <div class="top">{% block top %}{% endblock %}</div>
                <div class="center">{% block content %}{% endblock %}</div>
                <div class="bottom">{% block bottom %}{% endblock %}</div>

            </div>

	</div>
</body>
</html>

blog/templates/blog_detail.html
{% extends 'base.html' %}

{% block content %}

	<h1>Title: {{ blog.title }}</h1>

	<p><strong>Author: </strong><a href='{{ blog.blogger.get_absolute_url }}'>{{ blog.blogger.nik_name }}</a></p>
	<p><strong>Text: </strong>{{ blog.text }}</p>
	<p><strong>Data: </strong>{{ blog.date_of_public }}</p>

    <h3>Комментарии</h3>

     <a href='{% url 'comment-create' pk=blog.pk %}'>Добавить комментарий</a>

	{% for comment in comment_list %}

	    <p>{{ comment.text }} {{ comment.date_of_public }} {{ user.username }}</p>

	{% endfor %}

{% endblock %}

blog/templates/blog_form.html
{% extends 'base.html' %}

{% block content %}

<form method='post' action=''>
	{% csrf_token %}

		{{ form.as_p }}

		<input type='submit' value='Сохранить'>
</form>

{% endblock %}

blog/templates/blog_list.html
{% extends 'base.html' %}

{% block content %}

	<h1>Список блогов</h1>

	{% if blog_list %}

	<ul>
		{% for blog in blog_list %}

		<li><a href='{{ blog.get_absolute_url }}'>{{ blog.title }}</a> ({{ blog.date_of_public }}) - {{ blog.blogger.nik_name }}</li>

		{% endfor %}
	</ul>

	{% else %}

		<p>На платформе еще нет блогов</p>

	{% endif %}

{% endblock %}

blog/templates/blogger_detail.html
{% extends 'base.html' %}

{% block content %}

	<h1>Автор: {{ blogger.last_name }}, {{ blogger.first_name }}</h1>

    <p>Дата рождения: {{ blogger.date_of_birth }}</p>

	<p>О себе: {{ blogger.bio }}</p>

	<h4>Блоги</h4>

	{% for blog in blog_list %}

	<p><a href='{{ blog.get_absolute_url }}'>{{ blog.title }}</a></p>

	{% endfor %}

{% endblock %}

blog/templates/blogger_form.html
{% extends 'base.html' %}

{% block content %}

<form method='post' action=''>
	{% csrf_token %}

		{{ form.as_p }}

		<input type='submit' value='Сохранить'>
</form>

{% endblock %}

blog/templates/blogger_list.html
{% extends 'base.html' %}

{% block content %}

	<h1>Список блоггеров</h1>

	{% if blogger_list %}

	<ul>
		{% for blogger in blogger_list %}

		<li><a href='{{ blogger.get_absolute_url }}'>{{ blogger.nik_name }}</a></li>

		{% endfor %}
	</ul>

	{% else %}

		<p>На платформе еще нет блоггеров</p>

	{% endif %}

{% endblock %}

blog/templates/comment_form.html
{% extends 'base.html' %}

{% block content %}

<form method='post' action=''>
	{% csrf_token %}

		{{ form.as_p }}

		<input type='submit' value='Сохранить'>
</form>

{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}

{% block content %}

	<h1>Платформа для свободных писателей</h1>

	<p>Добро пожаловать на платформу, на которой Вы сможете писать обо всем!</p>

	<h2>Фонд блогов</h2>

	<p>Ресурс содержит следующие материалы:</p>

	<ul>
		<li><strong>Блоги:</strong>{{ num_blogs }}</li>
		<p></p>
		<li><strong>Блоггеры:</strong>{{ num_bloggers }}</li>
	</ul>

	<p>Вы посещали эту страницу {{ num_visits }}{% if num_visits == 1 %} раз{% else %} раза{% endif %}</p>

{% endblock %}

templates/django_registration/registration_complete.html
{% extends 'base.html' %}

{% block content %}

    <p>Вы зарегистрированы!</p>

    <p>Теперь Вы можете комментировать статьи блоггеров, а также стать блоггером</p>

{% endblock %}

templates/django_registration/registration_form.html
{% extends 'base.html' %}

{% block content %}

    <h1>Регистрация</h1>

	<form method='post' action=''>
	{% csrf_token %}

		{{ form.as_p }}

		<input type='submit' value='Отправить'>
	</form>

{% endblock %}